### ISSUE TITLE
Bugs in Decryption

### ISSUE THREAD

**Issue by MostafaMohamedAbelAzeem** [ahmedosama07/Hill-Cipher#8]
![image](https://github.com/ahmedosama07/Hill-Cipher/assets/106196247/6382b9a3-7b0c-474e-bfe3-c56062b5d30c)
![Bug](https://github.com/ahmedosama07/Hill-Cipher/assets/106196247/cb77b61e-eb8c-4637-9317-866289210348)

There is a problem in the functionality of the program. When a message is entered for encryption, and then we want to decrypt this message, the decryption is not done correctly.

**Comment by ahmedosama07** [comment]
This issue is solved in #9
